# Set up custom commands to run before & after Ctest run.
# 1. Start/stop Virtual Framebuffer for linux/bsd. 2. Pretty Print
# Please see the CTestCustom.template file for more info.
message(STATUS "creating CTestCustom.cmake")
set(TEMPLATE_HEADER "Generated by cmake from ${CCSD}/CTestCustom.template")
# Some stuff was removed from here used by the template engine.
# So we aren't using the templating feature any more.
# If you know how to get the file into the build directory or otherwise have ctest use it,
# feel free to remove this templating mechanism.
configure_file(${CCSD}/CTestCustom.template ${CBD}/CTestCustom.cmake @ONLY)
