# Set up custom commands to run before & after Ctest run.
# 1. Start/stop Virtual Framebuffer for linux/bsd. 2. Pretty Print
# Please see the CTestCustom.template file for more info.
message(STATUS "creating CTestCustom.cmake")
set(TEMPLATE_HEADER "Generated by cmake from ${CCSD}/CTestCustom.template")
set(UPLOADARG "")
if ($ENV{OPENSCAD_UPLOAD_TESTS})
  set(UPLOADARG "--upload")
endif()
# Normalize Python path to use forward slashes (required for CMake string parsing on Windows)
file(TO_CMAKE_PATH "${Python3_EXECUTABLE}" Python3_EXECUTABLE)
configure_file(${CCSD}/CTestCustom.template ${CBD}/CTestCustom.cmake @ONLY)
