#! /bin/sh

source scripts/setenv-macosx.sh
mkdir -p build
cd build
#cmake -DEXPERIMENTAL=1 -DENABLE_PYTHON=1 -DUSE_QT6=1 -DCMAKE_PREFIX_PATH=/usr/local/Qt-6.7.2 . 
#cmake -DEXPERIMENTAL=1 -DENABLE_PYTHON=1 -DUSE_QT6=1 -DCMAKE_PREFIX_PATH=/Users/apple/git/libraries -DCMAKE_OSX_ARCHITECTURES='x86_64;arm64' ..
cmake -DEXPERIMENTAL=1 -DENABLE_PYTHON=1 -DUSE_QT6=1 -DUSE_BUILTIN_CLIPPER2=ON -DCMAKE_PREFIX_PATH=/Users/apple/git/libraries ..
make -j3
pwd
VERSIONDATE=`date "+%Y.%m.%d"`
#/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $VERSIONDATE" OpenSCAD.app/Contents/Info.plist

/usr/local/Qt-6.7.2/bin/macdeployqt ./OpenSCAD.app -codesign=- -no-strip
cp -a /usr/local/lib/python3.12 OpenSCAD.app/Contents/Frameworks/
cp -a /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13 OpenSCAD.app/Contents/Frameworks
rm -rf __pycache__ site-packages/

rm OpenSCAD.dmg
hdiutil create -fs HFS+ -volname "PythonSCAD" -srcfolder "./OpenSCAD.app/" OpenSCAD.dmg

########
export PIP_TARGET=/Users/apple/git/openscad/build/OpenSCAD.app/Contents/Frameworks/python3.12
/usr/local/bin/python3.12 -m pip install numpy
