#!/usr/bin/env python

import re, sys, subprocess, os
from validatestl import validateSTL

scad_file = sys.argv[1]
openscad_bin = sys.argv[-2]
other_args = sys.argv[2:-2]

stlfile = scad_file + '.stl'

subprocess.check_call([openscad_bin, scad_file] + other_args + ['-o', stlfile])

ret = validateSTL(stlfile)
os.unlink(stlfile)

if not ret:
    sys.exit(1)
