#!/usr/bin/env python

import re, sys, subprocess

subprocess.check_call([sys.argv[2], sys.argv[1], '-o', sys.argv[3]])

result = open(sys.argv[3]).read()

result = re.sub(r', timestamp = [0-9]*', '', result)
result = re.sub(r'-?[0-9].[0-9]*e-[0-9]{2,}', '0', result)

open(sys.argv[3], 'w').write(result)
