// Generated by OpenSCAD (https://www.openscad.org/)
// Source file: cube.pov

// Camera settings are at the bottom of this script

#version 3.7;
global_settings { assumed_gamma 1.0 }
#declare MATERIAL=finish { specular 0.5 roughness 0.001 reflection{0 0.63 fresnel} ambient 0 diffuse 0.6 conserve_energy }
#declare MATERIAL_INT=interior{ior 1.32}
polygon { 5, 
<0, 0, 0>, <0, 0, 5>, <0, 5, 5>, <0, 5, 0>, <0, 0, 0>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 5, 
<0, 0, 0>, <0, 5, 0>, <5, 5, 0>, <5, 0, 0>, <0, 0, 0>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 5, 
<0, 0, 0>, <5, 0, 0>, <5, 0, 5>, <0, 0, 5>, <0, 0, 0>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 5, 
<0, 0, 5>, <5, 0, 5>, <5, 5, 5>, <0, 5, 5>, <0, 0, 5>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 5, 
<0, 5, 0>, <0, 5, 5>, <5, 5, 5>, <5, 5, 0>, <0, 5, 0>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 5, 
<5, 0, 0>, <5, 5, 0>, <5, 5, 5>, <5, 0, 5>, <5, 0, 0>
texture { pigment { color rgbf <0.976471, 0.843137, 0.172549, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
light_source { <-10, -10, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, -10, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, -10, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 2.5, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 2.5, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 2.5, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 15, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 15, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <-10, 15, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, -10, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, -10, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, -10, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 2.5, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 2.5, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 2.5, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 15, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 15, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <2.5, 15, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <15, -10, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <15, -10, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <15, -10, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 2.5, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 2.5, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 2.5, 15> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 15, -10> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 15, 2.5> color rgb <0.2, 0.2, 0.2> }
light_source { <15, 15, 15> color rgb <0.2, 0.2, 0.2> }
camera { look_at <0, 0, 0>
 location <0, 0, 140>
 angle 22.5 up <0, 1, 0> right <1, 0, 0> sky <0, 1, 0> right -x*image_width/image_height
translate <0, 0, 0>
rotate <55, 0 + clock * 3, 25 + clock>
}
#include "rad_def.inc"
global_settings { photons { count 20000 autostop 0 jitter .4 } radiosity { Rad_Settings(Radiosity_Normal, off, off) } }
