schema: 1
notes: Base distro definitions (shared across profiles). Profiles add or extend packages
  without redefining managers.
distros:
  debian:
    manager: apt
    pre_commands:
    - apt-get update
    post_commands: []
    packages:
    - bison
    - build-essential
    - cmake
    - curl
    - flex
    - gettext
    - ghostscript
    - git
    - gtk-doc-tools
    - imagemagick
    - lib3mf-dev
    - libboost-program-options-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libcairo2-dev
    - libcgal-dev
    - libdouble-conversion-dev
    - libeigen3-dev
    - libffi-dev
    - libfontconfig-dev
    - libfreetype-dev
    - libgl1-mesa-dev
    - libglew-dev
    - libglib2.0-dev
    - libgmp-dev
    - libharfbuzz-dev
    - libmimalloc-dev
    - libmpfr-dev
    - libopencsg-dev
    - libqt5gamepad5-dev
    - libtbb-dev
    - libxi-dev
    - libxml2-dev
    - libxmu-dev
    - libzip-dev
    - nettle-dev
    - ninja-build
    - nodejs
    - pkg-config
    - python3-dev
    - python3-setuptools
    - python3-venv
    - ragel
    - xvfb
    version_overrides:
      '12':
        add: []
        remove: []
  ubuntu:
    extends: debian
    version_overrides:
      '24':
        add: []
        remove: []
  fedora:
    manager: dnf
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - boost-devel
    - cairo-devel
    - ccache
    - CGAL-devel
    - cmake
    - curl
    - double-conversion-devel
    - eigen3-devel
    - flex
    - fontconfig-devel
    - freetype-devel
    - gcc
    - gcc-c++
    - gettext
    - ghostscript
    - git
    - glew-devel
    - glib2-devel
    - gmp-devel
    - gtk-doc
    - harfbuzz-devel
    - ImageMagick
    - lib3mf-devel
    - libffi-devel
    - libXi-devel
    - libxml2-devel
    - libXmu-devel
    - libzip-devel
    - make
    - mesa-dri-drivers
    - mesa-libGL-devel
    - mimalloc-devel
    - mpfr-devel
    - nettle-devel
    - ninja-build
    - nodejs
    - opencsg-devel
    - pkgconfig
    - python3
    - python3-devel
    - python3-setuptools
    - qtchooser
    - ragel
    - redhat-rpm-config
    - tbb-devel
    - xorg-x11-server-Xvfb
    version_overrides:
      '42':
        add: []
        remove: []
  arch:
    manager: pacman
    pre_commands:
    - pacman -Syu --noconfirm
    post_commands: []
    packages:
    - base-devel
    - bison
    - boost
    - cairo
    - cgal
    - cmake
    - curl
    - double-conversion
    - eigen
    - flex
    - fontconfig
    - freetype2
    - gcc-libs
    - gettext
    - ghostscript
    - git
    - glew
    - glib2
    - glibc
    - glu
    - gmp
    - gtk-doc
    - harfbuzz
    - hicolor-icon-theme
    - hidapi
    - imagemagick
    - lib3mf
    - libffi
    - libglvnd
    - libspnav
    - libx11
    - libxi
    - libxml2
    - libxmu
    - libzip
    - mesa
    - mimalloc
    - mpfr
    - nettle
    - ninja
    - nodejs
    - opencsg
    - pkgconf
    - procps-ng
    - python
    - python-pip
    - python-setuptools
    - ragel
    - tbb
    - xorg-server-xvfb
    version_overrides: {}
  gentoo:
    manager: emerge
    pre_commands:
    - emerge --sync
    post_commands: []
    packages:
    - app-text/ghostscript
    - dev-cpp/tbb
    - dev-lang/python
    - dev-libs/boost
    - dev-libs/gmp
    - dev-libs/libffi
    - dev-libs/libxml2
    - dev-libs/libzip
    - dev-libs/mpfr
    - dev-libs/nettle
    - dev-util/cmake
    - dev-util/ninja
    - dev-util/ragel
    - dev-vcs/git
    - media-gfx/imagemagick
    - media-libs/fontconfig
    - media-libs/freetype
    - media-libs/glew
    - media-libs/harfbuzz
    - media-libs/lib3mf
    - media-libs/mesa
    - media-libs/opencsg
    - net-misc/curl
    - sci-libs/eigen
    - sci-mathematics/cgal
    - sys-devel/bison
    - sys-devel/flex
    - sys-devel/gcc
    - sys-devel/gettext
    - x11-base/xorg-server
    - x11-libs/cairo
    - x11-libs/libXi
    - x11-libs/libXmu
    version_overrides: {}
  freebsd:
    manager: pkg
    pre_commands: []
    post_commands: []
    packages:
    - bash
    - bison
    - boost-libs
    - cairo
    - cgal
    - cmake
    - curl
    - double-conversion
    - eigen3
    - flex
    - fontconfig
    - freetype2
    - gettext
    - ghostscript
    - git
    - glew
    - glib
    - gmake
    - gmp
    - gtk-doc
    - harfbuzz
    - ImageMagick7
    - libffi
    - libGLU
    - libXi
    - libxml2
    - libXmu
    - libzip
    - mesa-libs
    - mimalloc
    - mpfr
    - nettle
    - ninja
    - node
    - onetbb
    - opencsg
    - pkgconf
    - python3
    - py39-setuptools
    - ragel
    - xorg
    - xorg-vfbserver
    version_overrides: {}
  netbsd:
    manager: pkgin
    pre_commands: []
    post_commands: []
    packages:
    - bash
    - bison
    - boost
    - cairo
    - cgal
    - cmake
    - curl
    - eigen3
    - flex
    - fontconfig
    - freetype2
    - gettext
    - ghostscript
    - git
    - glew
    - glib2
    - gmake
    - gmp
    - gtk-doc
    - harfbuzz
    - ImageMagick
    - libffi
    - libxml2
    - libzip
    - mesa
    - mimalloc
    - mpfr
    - nettle
    - ninja
    - nodejs
    - opencsg
    - python3
    - ragel
    - threadingbuildingblocks
    version_overrides: {}
  macos:
    manager: brew
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - boost
    - cairo
    - cgal
    - cmake
    - curl
    - double-conversion
    - eigen
    - flex
    - fontconfig
    - freetype
    - gettext
    - ghostscript
    - git
    - glew
    - glib
    - gmp
    - gtk-doc
    - harfbuzz
    - imagemagick
    - libffi
    - libxml2
    - libzip
    - mimalloc
    - mpfr
    - nettle
    - ninja
    - node
    - opencsg
    - pkg-config
    - python@3.12
    - ragel
    - tbb
    version_overrides: {}
  opensuse:
    manager: zypper
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - boost-devel
    - cairo-devel
    - cgal-devel
    - cmake
    - curl
    - double-conversion-devel
    - flex
    - fontconfig-devel
    - freetype-devel
    - gcc-c++
    - gettext
    - ghostscript
    - git
    - glew-devel
    - glib2-devel
    - gmp-devel
    - gtk-doc
    - harfbuzz-devel
    - ImageMagick
    - lib3mf-devel
    - libeigen3-devel
    - libffi-devel
    - libXi-devel
    - libxml2-devel
    - libXmu-devel
    - libzip-devel
    - Mesa-devel
    - mimalloc-devel
    - mpfr-devel
    - nettle-devel
    - ninja
    - nodejs
    - opencsg-devel
    - pkg-config
    - python3
    - python3-devel
    - python3-setuptools
    - ragel
    - tbb-devel
    - xvfb-run
    version_overrides: {}
  mageia:
    manager: urpmi
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - cmake
    - curl
    - double-conversion-devel
    - eigen3-devel
    - flex
    - gettext
    - ghostscript
    - git
    - glib2-devel
    - imagemagick
    - lib3mf-devel
    - libboost-devel
    - libcairo-devel
    - libffi-devel
    - libglew-devel
    - libgmp-devel
    - libmesa-devel
    - libmpfr-devel
    - libxi-devel
    - libxml2-devel
    - libxmu-devel
    - libzip-devel
    - nettle-devel
    - ninja
    - nodejs
    - python3
    - python3-devel
    - python3-setuptools
    - task-c++-devel
    - task-c-devel
    - tbb
    - x11-server-xvfb
    version_overrides: {}
  solus:
    manager: eopkg
    pre_commands:
    - eopkg -y it -c system.devel
    post_commands: []
    packages:
    - bison
    - cairo-devel
    - CGAL-devel
    - cmake
    - curl
    - double-conversion-devel
    - eigen3
    - flex
    - fontconfig-devel
    - freetype2-devel
    - gettext-devel
    - ghostscript
    - git
    - glew-devel
    - glib2-devel
    - gmp-devel
    - harfbuzz-devel
    - imagemagick
    - intel-tbb-devel
    - libffi-devel
    - libxml2-devel
    - libzip-devel
    - mesalib-devel
    - mpfr-devel
    - ninja
    - nodejs
    - opencsg-devel
    - pkg-config-devel
    - python3
    - python3-devel
    - system.devel
    version_overrides: {}
  altlinux:
    manager: apt
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - boost-devel
    - boost-program_options-devel
    - boost-regex-devel
    - boost-system-devel
    - boost-thread-devel
    - cmake
    - curl
    - eigen3
    - flex
    - gcc4.5
    - gcc4.5-c++
    - gettext
    - ghostscript
    - git-core
    - glib2-devel
    - imagemagick
    - lib3mf-devel
    - libcgal-devel
    - libffi-devel
    - libglew-devel
    - libgmp
    - libgmp_cxx-devel
    - libmimalloc-devel
    - libmpfr
    - libxml2-devel
    - libzip-devel
    - nettle-devel
    - ninja-build
    - nodejs
    - pkg-config
    - python3
    - python3-devel
    - python3-setuptools
    - ragel
    - tbb-devel
    version_overrides: {}
  qomo:
    manager: dnf
    pre_commands: []
    post_commands: []
    packages:
    - bison
    - boost-devel
    - cairo-devel
    - CGAL-devel
    - cmake
    - curl
    - double-conversion-devel
    - eigen3-devel
    - flex
    - fontconfig-devel
    - freetype-devel
    - gcc
    - gcc-c++
    - gettext
    - ghostscript
    - git
    - glew-devel
    - glib2-devel
    - gmp-devel
    - gtk-doc
    - harfbuzz-devel
    - ImageMagick
    - lib3mf-devel
    - libffi-devel
    - libXi-devel
    - libxml2-devel
    - libXmu-devel
    - libzip-devel
    - make
    - mesa-dri-drivers
    - mesa-libGL-devel
    - mimalloc-devel
    - mpfr-devel
    - nettle-devel
    - ninja-build
    - nodejs
    - opencsg-devel
    - pkgconfig
    - python3
    - python3-devel
    - python3-setuptools
    - ragel
    - tbb-devel
    - xorg-x11-server-Xvfb
    version_overrides: {}
