echo(undef);
echo("string");
s = "stringvar";
echo(s);
echo(a = 1, b = 2.0, true, c = false);
v = [1, "vecstr", 2.34, false];
echo(v);
r = [1:2:10];
echo(r);

echo(vec = [1,2,3]);
echo(range = [0:2]);

echo(str("string generated by str()"));
