#!/usr/bin/env bash
#
# Bundle PythonSCAD's runtime Python dependencies (currently: IPython)
# into a destination directory that ships alongside a release binary.
#
# This script is the single source of truth for "what gets bundled into
# AppImage / macOS .app / Windows installer". Every binary distribution
# pipeline calls this script with a destination path that maps to one of
# the directories pythonscad's `initPython` searches at startup:
#
#   * AppImage   -> ${APPDIR}/usr/lib/pythonscad-bundled-py
#   * macOS .app -> <App>.app/Contents/Resources/pythonscad-bundled-py
#   * Windows    -> <staging>/lib/pythonscad-bundled-py
#
# The bundled directory is *appended* to sys.path inside `initPython`,
# which means a system-installed IPython (anything earlier on sys.path
# such as a venv, --user site, or distro package) wins over the bundle.
# The bundle is therefore strictly a fallback for self-contained binary
# distributions where the user has no other Python interpreter handy.
#
# Two artefacts are produced inside the destination directory:
#
#   1. The pip-installed packages from `requirements/runtime.txt`.
#   2. THIRD_PARTY_LICENSES.txt, generated by pip-licenses, which
#      enumerates the licenses of every bundled wheel. This file is
#      what the AppImage/.app/Installer ships next to its own COPYING.
#
# Usage:
#   bundle-runtime-python.sh <destination-dir> [--python <interpreter>]
#
# Required: destination-dir (created if missing).
# Optional: --python <interpreter>   pip target Python (default: python3)
#           --requirements <file>    override requirements file path
#           --no-licenses            skip THIRD_PARTY_LICENSES.txt step
#
# Exit codes:
#   0  success
#   1  unrecoverable error (bad arguments, pip install failed, ...)
#   2  pip-licenses missing AND --no-licenses not given. The license
#      file is mandatory for redistributable bundles, so the script
#      refuses to proceed silently. CI installs pip-licenses up front.

set -euo pipefail

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

info()  { echo -e "${GREEN}[bundle-py]${NC} $*"; }
warn()  { echo -e "${YELLOW}[bundle-py]${NC} $*" >&2; }
error() { echo -e "${RED}[bundle-py]${NC} $*" >&2; }
die()   { error "$*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DEST=""
PYTHON_BIN="${PYTHON:-python3}"
REQUIREMENTS="${PROJECT_ROOT}/requirements/runtime.txt"
WITH_LICENSES=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --python)
            # `set -u` would otherwise turn a missing value into a
            # cryptic "unbound variable" error; the explicit check
            # gives the user a clear usage message instead.
            [[ $# -ge 2 ]] || die "missing value for --python"
            PYTHON_BIN="$2"
            shift 2
            ;;
        --requirements)
            [[ $# -ge 2 ]] || die "missing value for --requirements"
            REQUIREMENTS="$2"
            shift 2
            ;;
        --no-licenses)
            WITH_LICENSES=0
            shift
            ;;
        -h|--help)
            sed -n '2,40p' "$0"
            exit 0
            ;;
        --*)
            die "unknown option: $1"
            ;;
        *)
            if [[ -z "${DEST}" ]]; then
                DEST="$1"
            else
                die "unexpected positional argument: $1"
            fi
            shift
            ;;
    esac
done

[[ -n "${DEST}" ]] || die "destination directory is required"
[[ -f "${REQUIREMENTS}" ]] || die "requirements file not found: ${REQUIREMENTS}"
command -v "${PYTHON_BIN}" >/dev/null 2>&1 \
    || die "python interpreter not found: ${PYTHON_BIN}"

# Defense-in-depth for the `rm -rf "${DEST}"` we do at the end of
# Step 1: refuse obviously dangerous destinations *before* touching
# the filesystem. The `[[ -n "${DEST}" ]]` check above already
# rejects empty/missing, but a caller passing literal `/`, `//`,
# `.`, or `..` would slip through and eat the parent directory on
# the swap.
#
# Layer 1 - literal blocklist (cheapest path; trips before any
# subprocess work). Catches the plain text forms that have no
# legitimate use as a bundle destination.
case "${DEST}" in
    /|//|.|..|/..|../|"./..") die "refusing to use \"${DEST}\" as bundle destination" ;;
esac
#
# Layer 2 - resolved blocklist. Normalise the path with
# `os.path.realpath(os.path.abspath(...))`:
#   * `abspath` makes relative inputs absolute relative to CWD.
#   * `realpath` resolves symlinks too, so `DEST=/tmp/symlink`
#     pointing at `/usr` is rejected as `/usr`, not accepted as
#     `/tmp/symlink`. (Copilot review, PR #600 thread on
#     scripts/bundle-runtime-python.sh:123.)
# Both are pure-Python pathlib operations that work uniformly on
# Linux / macOS / MSYS2/UCRT64 without depending on the
# differently-flavoured `realpath -m` of GNU vs BSD coreutils.
#
# Filesystem-root rejection is delegated to Python (`os.path.dirname(p)
# == p`) instead of being case-pattern-matched here because (a) it is
# platform-native -- works for POSIX `/`, Windows `C:\`, and UNC
# `\\server\share` without extra glob arms -- and (b) the bash case
# below is restricted to the named POSIX directory blocklist where
# Windows drive-letter syntax (`C:\Users`) is irrelevant. Without the
# Python-side check, a Windows caller passing literal `C:\` would
# slip past the case statement and hit `rm -rf "${DEST:?}"`.
# (Copilot review, PR #600 thread on
# scripts/bundle-runtime-python.sh:143.)
RESOLVED_DEST="$("${PYTHON_BIN}" -c '
import os, sys
p = os.path.realpath(os.path.abspath(sys.argv[1]))
if os.path.dirname(p) == p:
    sys.stderr.write(
        f"refusing to use \"{p}\" as bundle destination "
        f"(resolved from \"{sys.argv[1]}\"): path is a filesystem root\n")
    sys.exit(2)
print(p)
' "${DEST}")" || die "destination path validation failed for \"${DEST}\""
# `${HOME:-/__pythonscad_home_unset__}` keeps the case pattern
# valid under `set -u` even when HOME is not exported (e.g. some
# minimal-env CI containers, systemd unit shells, packaging
# chroots). The sentinel path is intentionally implausible as a
# real `RESOLVED_DEST` so an unset HOME degrades to "no HOME
# match" rather than "HOME: unbound variable" abort.
case "${RESOLVED_DEST}" in
    /usr|/usr/local|/opt|/etc|/var|"${HOME:-/__pythonscad_home_unset__}"|/home|/root)
        die "refusing to use \"${RESOLVED_DEST}\" as bundle destination (resolved from \"${DEST}\")"
        ;;
esac

info "Bundling runtime Python deps:"
info "  destination:  ${DEST}"
info "  interpreter:  ${PYTHON_BIN} ($("${PYTHON_BIN}" --version 2>&1))"
info "  requirements: ${REQUIREMENTS}"

# Step 1: install the runtime requirements into a fresh staging dir,
# then swap that staging dir into place at ${DEST}.
#
# `--target` lays the wheels out flat (no venv structure) which is what
# the embedded interpreter expects when this directory is added to
# sys.path.
#
# We MUST install into a clean directory rather than re-using ${DEST}
# from a previous run: `pip install --target ... --upgrade` only
# add/upgrades packages, it does NOT prune packages that used to be in
# requirements/runtime.txt but are not anymore. Re-running into ${DEST}
# in place would leave stale wheels and stale `*.dist-info/` metadata
# behind, which would silently leak into the bundle AND into the
# pip-licenses-generated THIRD_PARTY_LICENSES.txt below.
#
# The atomic swap pattern (install into a sibling staging dir, then
# `rm -rf ${DEST}` + `mv staging ${DEST}`) keeps the rebuild
# idempotent: the contents of ${DEST} after a successful run are
# exactly the requirements set, with no carry-over from prior runs.
DEST_PARENT="$(dirname "${DEST}")"
DEST_NAME="$(basename "${DEST}")"
mkdir -p "${DEST_PARENT}"
STAGING_DEST="$(mktemp -d "${DEST_PARENT}/${DEST_NAME}.tmp.XXXXXX")"

cleanup_staging() {
    # On any error path before the final mv, drop the staging dir so
    # we don't leave garbage next to the real destination.
    # `${STAGING_DEST:?}` makes `rm -rf` abort loudly if STAGING_DEST
    # ever ends up empty/unset (e.g. mktemp was bypassed) instead of
    # silently expanding to `rm -rf` (no-op) or worse.
    [[ -d "${STAGING_DEST}" ]] && rm -rf "${STAGING_DEST:?}"
}
trap cleanup_staging EXIT

is_msys2_python() {
    # Key off the interpreter's platform tag (mingw_* on MSYS2 builds),
    # not MSYSTEM, so a python.org CPython invoked inside an MSYS2 shell
    # still takes the normal pip install path.
    "${PYTHON_BIN}" -c '
import sys, sysconfig
raise SystemExit(0 if sys.platform == "win32" and "mingw" in sysconfig.get_platform() else 1)
' 2>/dev/null
}

if is_msys2_python; then
    info "MSYS2 detected; using pacman-vendored psutil path for IPython 9+"
    "${PYTHON_BIN}" "${SCRIPT_DIR}/bundle-ipython-msys2.py" \
        --python "${PYTHON_BIN}" \
        --target "${STAGING_DEST}" \
        --requirements "${REQUIREMENTS}" \
        || die "MSYS2 IPython bundle install into ${STAGING_DEST} failed"
else
    info "Running pip install --target=${STAGING_DEST} -r ${REQUIREMENTS}"
    "${PYTHON_BIN}" -m pip install \
        --target "${STAGING_DEST}" \
        --upgrade \
        --no-compile \
        -r "${REQUIREMENTS}" \
        || die "pip install into ${STAGING_DEST} failed"
fi

# Prune jedi's bundled third-party type stubs.
#
# IPython depends on jedi for autocompletion. jedi's wheel ships a
# `jedi/third_party/` directory with type stubs for popular Python
# frameworks (django, flask, requests, attrs, ...). Two reasons to drop
# these from the PythonSCAD bundle:
#
#   1. Path-length blowup on Windows: NSIS's makensis.exe uses the
#      Win32 ANSI file APIs and is therefore subject to the legacy
#      MAX_PATH (260 chars) limit. The deepest django-stubs paths --
#      `jedi/third_party/django-stubs/django-stubs/contrib/contenttypes/
#      management/commands/remove_stale_contenttypes.pyi` -- combined
#      with CPack's already-long `_CPack_Packages/<arch>/NSIS/<long
#      versioned installer name>/` staging prefix push past 260 chars
#      and abort installer generation (pythonscad/pythonscad#600 review
#      flow). Pruning the third-party tree shortens the deepest path
#      well below the limit.
#   2. Dead weight: PythonSCAD users are not authoring django/flask/...
#      code in the embedded IPython prompt, so the stubs provide no
#      autocompletion value and just inflate the bundle by ~7 MB.
#
# Applied universally (Linux/macOS/Windows) for consistency: the macOS
# .app and the AppImage also benefit from the size reduction, and a
# uniform layout is easier to reason about than a Windows-only patch.
JEDI_THIRD_PARTY="${STAGING_DEST}/jedi/third_party"
if [[ -d "${JEDI_THIRD_PARTY}" ]]; then
    info "Pruning ${JEDI_THIRD_PARTY} ($(du -sh "${JEDI_THIRD_PARTY}" 2>/dev/null | awk '{print $1}'))"
    rm -rf "${JEDI_THIRD_PARTY:?}"
fi

# Atomically replace any existing destination with the freshly
# populated staging dir. `mv` is atomic for same-filesystem renames,
# which is guaranteed here because STAGING_DEST is a sibling of DEST.
# `${DEST:?}` is paranoia in depth on top of the upfront validation
# block above: even if someone slips an unset DEST past the guards,
# bash will abort `rm` with a clear "DEST: parameter null or not set"
# instead of expanding to a bare `rm -rf`.
rm -rf "${DEST:?}"
mv "${STAGING_DEST}" "${DEST}"
trap - EXIT

# Step 2: emit THIRD_PARTY_LICENSES.txt next to the bundled wheels.
#
# We point pip-licenses at the destination directory so the report
# reflects exactly what we shipped, not whatever happens to be in the
# build host's site-packages. This also avoids polluting the CI build
# environment with extra packages.
if [[ "${WITH_LICENSES}" -eq 1 ]]; then
    if ! "${PYTHON_BIN}" -c "import piplicenses" >/dev/null 2>&1; then
        # `pip-licenses` is intentionally NOT in requirements/runtime.txt
        # (it is a build-time tool, not a runtime dependency the user's
        # scripts can import). Distributors must install it themselves;
        # CI does this in the workflow step that calls us.
        if [[ "${BUNDLE_PY_AUTO_INSTALL_PIP_LICENSES:-0}" = "1" ]]; then
            warn "pip-licenses missing; auto-installing because BUNDLE_PY_AUTO_INSTALL_PIP_LICENSES=1"
            # PEP 668 hosts (Homebrew Python on macOS, Debian/Ubuntu
            # system Python, MSYS2 ucrt64) refuse `pip install` into
            # their site-packages without `--break-system-packages`.
            # Try the modern flag first; fall back to plain pip for
            # older pip releases (<23.0.1) that don't recognise it
            # AND aren't PEP 668-managed in the first place. A final
            # plain attempt without `--quiet` runs only if both prior
            # attempts fail, so the user sees the real error message
            # before we `die`.
            "${PYTHON_BIN}" -m pip install --quiet --break-system-packages pip-licenses 2>/dev/null \
                || "${PYTHON_BIN}" -m pip install --quiet pip-licenses 2>/dev/null \
                || "${PYTHON_BIN}" -m pip install --break-system-packages pip-licenses \
                || die "auto-install of pip-licenses failed"
        else
            error "pip-licenses is not installed in ${PYTHON_BIN}."
            error "Install it (e.g. 'pip install pip-licenses') or pass"
            error "--no-licenses to skip the bundled licenses report."
            exit 2
        fi
    fi

    LICENSES_OUT="${DEST}/THIRD_PARTY_LICENSES.txt"
    info "Generating ${LICENSES_OUT}"

    # Restrict pip-licenses to *only* the packages we installed under
    # ${DEST}. Two filters are in play:
    #
    #   1. We monkey-patch `importlib.metadata.distributions` so it
    #      yields only distributions whose on-disk location lives
    #      under ${DEST}. Without this, pip-licenses uses the build
    #      host's site-packages too (since `python -m piplicenses`
    #      runs with site.py initialized) and we'd ship a license
    #      report that conflates bundled and host wheels - making
    #      the "drift detector" intent unreliable.
    #   2. We *also* pass `--packages` enumerated from the bundle's
    #      `*.dist-info` directories. This is belt-and-suspenders:
    #      if (1) ever regresses, (2) still keeps the package list
    #      bounded.
    BUNDLED_PACKAGES=()
    while IFS= read -r -d '' dist_info; do
        # Read the canonical distribution name from the dist-info's
        # METADATA `Name:` field rather than parsing it out of the
        # directory name. The `${pkg_name%-*}` form works for the
        # PEP 440 happy path (versions without `-`), but PEP 566 says
        # the METADATA `Name:` field is the authoritative source, and
        # the parsing approach silently mis-extracts the name on
        # legacy version strings such as `setuptools-58.0-rc1` (which
        # would yield `setuptools-58.0` instead of `setuptools`).
        # Reading METADATA is robust against any weirdly-formed
        # version, build tag, or local-version-segment scheme.
        metadata_file="${dist_info}/METADATA"
        [[ -f "${metadata_file}" ]] \
            || die "missing METADATA in ${dist_info}; cannot determine distribution name for license report"

        pkg_name="$(sed -n 's/^Name:[[:space:]]*//p' "${metadata_file}" | head -n 1)"
        [[ -n "${pkg_name}" ]] \
            || die "missing Name field in ${metadata_file}; cannot determine distribution name for license report"

        BUNDLED_PACKAGES+=("${pkg_name}")
    done < <(find "${DEST}" -maxdepth 2 -name "*.dist-info" -type d -print0 2>/dev/null)

    if [[ ${#BUNDLED_PACKAGES[@]} -eq 0 ]]; then
        die "no .dist-info directories found under ${DEST}; cannot generate license report"
    fi

    info "Reporting on ${#BUNDLED_PACKAGES[@]} bundled package(s): ${BUNDLED_PACKAGES[*]}"

    # `mktemp --suffix=.py` is a GNU extension; macOS ships BSD
    # mktemp which doesn't accept --suffix. Use a portable template
    # under $TMPDIR (or /tmp) and rename to add the .py extension
    # so Python recognises the file as a script.
    PIP_LICENSES_WRAPPER_BASE="$(mktemp "${TMPDIR:-/tmp}/bundle-py-piplic-XXXXXXXX")"
    PIP_LICENSES_WRAPPER="${PIP_LICENSES_WRAPPER_BASE}.py"
    mv "${PIP_LICENSES_WRAPPER_BASE}" "${PIP_LICENSES_WRAPPER}"

    cat > "${PIP_LICENSES_WRAPPER}" <<'WRAPPER_EOF'
"""Run pip-licenses scoped to a single sys.path target directory.

Argument vector layout:
    sys.argv = [<this file>, <target_dir>, <pip-licenses args...>]

The wrapper:
  1. Inserts <target_dir> at sys.path[0] so pip-licenses imports
     (and reads METADATA / LICENSE files from) the bundled wheels
     in preference to any older host copies of the same name. This
     replaces a previous `PYTHONPATH=...` shell-side approach which
     was non-portable across `:`-separator (POSIX) and `;`-separator
     (Windows native Python) hosts.
  2. Monkey-patches importlib.metadata.distributions to yield only
     distributions whose installed files live under <target_dir>,
     so the host's site-packages don't leak into the report.
  3. Hands off to piplicenses.main() with the remaining argv.
"""
import os
import sys
import importlib.metadata as md

target_dir = os.path.realpath(sys.argv[1])
sys.argv[1:] = sys.argv[2:]

# Step (1): make the bundle preferred for any imports pip-licenses
# does on its own (e.g. reading wheel metadata via importlib).
if target_dir not in sys.path:
    sys.path.insert(0, target_dir)

# Step (2): scope distribution enumeration to the bundle.
_real_distributions = md.distributions


def _scoped_distributions(*args, **kwargs):
    for dist in _real_distributions(*args, **kwargs):
        loc = dist.locate_file("")
        try:
            loc_str = os.path.realpath(str(loc))
        except (TypeError, ValueError):
            continue
        if loc_str.startswith(target_dir + os.sep) or loc_str == target_dir:
            yield dist


md.distributions = _scoped_distributions

# pip-licenses 4.x and 5.x both expose `main` at module top-level.
from piplicenses import main as piplicenses_main  # noqa: E402

sys.exit(piplicenses_main() or 0)
WRAPPER_EOF

    "${PYTHON_BIN}" \
        "${PIP_LICENSES_WRAPPER}" \
        "${DEST}" \
        --from=mixed \
        --format=plain-vertical \
        --with-license-file \
        --with-urls \
        --with-authors \
        --no-license-path \
        --packages "${BUNDLED_PACKAGES[@]}" \
        --output-file "${LICENSES_OUT}" \
        || { rm -f "${PIP_LICENSES_WRAPPER}"; die "pip-licenses failed to generate ${LICENSES_OUT}"; }
    rm -f "${PIP_LICENSES_WRAPPER}"

    # Prepend a header that pins down what the file is. pip-licenses
    # itself only emits raw entries; consumers reading
    # THIRD_PARTY_LICENSES.txt deserve a one-paragraph explanation.
    #
    # Use a portable mktemp template: bare `mktemp` works on GNU but
    # fails on BSD/macOS (which require an explicit template). The
    # macOS release workflow runs this script, so we have to support
    # both. Same shape as the pip-licenses wrapper-file mktemp above.
    HEADER_FILE="$(mktemp "${TMPDIR:-/tmp}/bundle-py-header-XXXXXXXX")"
    cat > "${HEADER_FILE}" <<'HEADER_EOF'
THIRD-PARTY LICENSES
====================

This file lists the licenses of the third-party Python packages
bundled inside this PythonSCAD distribution under the
"pythonscad-bundled-py" directory. The list is generated automatically
at build time by scripts/bundle-runtime-python.sh and reflects the
exact wheels shipped alongside the binary.

PythonSCAD itself is licensed under the GNU General Public License
v2 or later; see the COPYING file shipped next to this report.

----------------------------------------------------------------------

HEADER_EOF
    cat "${HEADER_FILE}" "${LICENSES_OUT}" > "${LICENSES_OUT}.tmp"
    mv "${LICENSES_OUT}.tmp" "${LICENSES_OUT}"
    rm -f "${HEADER_FILE}"
fi

# Sanity-check: the bundle must at least be importable as `IPython`.
#
# We pass the bundle directory in via argv and have the smoke probe
# insert it into sys.path itself rather than relying on PYTHONPATH.
# PYTHONPATH uses `:` as the separator on POSIX and `;` on Windows
# native Python; doing the path-mutation in Python makes the call
# site cross-platform without any per-host quoting tricks.
info "Smoke-checking bundle (import IPython, psutil)"
"${PYTHON_BIN}" - "${DEST}" <<'PY' || die "bundle smoke check failed"
import sys
sys.path.insert(0, sys.argv[1])
import IPython
import psutil
print("[bundle-py] bundled IPython:", IPython.__version__, "from", IPython.__file__)
print("[bundle-py] bundled psutil:", psutil.__version__, "from", psutil.__file__)
PY

info "Bundle complete: $(du -sh "${DEST}" | cut -f1) at ${DEST}"
