//They are expected to work the same way as without the  trailing comma 
//fucntion call test

$a = 1;
b = 1;
echo(let() $a*b);
echo(let($a=2,b=3,) $a*b);
echo(let(b=2,$a=3,) $a*b);
echo(let($a=2,) $a*b);
echo(let(b=3,) $a*b);
echo(let($a=2,b=3,$a=4,) $a*b);
echo(let($a=2,b=3,b=5,) $a*b);
echo(let($a=2,b=3,$a=4,b=5,) $a*b);
echo(let($a=2,b=$a*3,) $a*b);
echo(let($a=2*b,b=3,) $a*b);
echo(let($a=2*b,b=$a*3,) $a*b);
echo(let(b=$a*3,$a=2*b,) $a*b);

echo(let(b=$a,$a=b,) [$a, b]);
echo(let(b=2*$a,$a=b,) [for (i=[1:b]) [i,$a]]);

//functions and modules can have unnamend parameters
//but this does not make sense for let
let(42,);
let(1,2,3,4,);

//assert test
a = 3;
b = 6;

assert(true,);

assert("t1",);

assert(a*b,);

assert(condition = a*b,);

assert(true) cube(8, center = true,);

c = 2;
translate([0, 20, 0])
assert(condition = 2,)
sphere(5);

d = c + 9;
assert(condition = d + 5 > 15, message = str("value: ", d + 5),)
translate([15, 0, 0])
cylinder(8, 5, center = true);

echo("assert-tests",);

//echo test
echo(undef,);
echo("string",);
s = "stringvar";
echo(s,);
echo(a = 1, b = 2.0, true, c = false,);
v = [1, "vecstr", 2.34, false];
echo(v,);
r = [1:2:10];
echo(r);

echo(vec = [1,2,3],);
echo(range = [0:2],);

echo(str("string generated by str()"),);
