# Default to today's date
if ("${OPENSCAD_VERSION}" STREQUAL "")
  string(TIMESTAMP OPENSCAD_VERSION "%Y.%m.%d")
endif()
# Split OPENSCAD_VERSION into components
# YYYY.MM-PPP
# YYYY.MM.DD-PPP
# YYYY.MM.DD.build
string(REGEX MATCH "^(([0-9]+)\\.([0-9]+)(\\.([0-9]+))?)(-([^\\.]+))?(\\.(.*))?$" MATCH "${OPENSCAD_VERSION}")

set(OPENSCAD_SHORTVERSION ${CMAKE_MATCH_1})
set(OPENSCAD_YEAR ${CMAKE_MATCH_2})
set(OPENSCAD_MONTH ${CMAKE_MATCH_3})
math(EXPR OPENSCAD_MONTH ${OPENSCAD_MONTH}) # get rid of leading zero
set(OPENSCAD_DAY ${CMAKE_MATCH_5})
if (DEFINED OPENSCAD_DAY)
  math(EXPR OPENSCAD_DAY ${OPENSCAD_DAY}) # get rid of leading zero
endif()
set(OPENSCAD_PATCH ${CMAKE_MATCH_7})
set(OPENSCAD_BUILD ${CMAKE_MATCH_9})

set(PROJECT_VERSION ${OPENSCAD_SHORTVERSION})

# message(STATUS "OPENSCAD_SHORTVERSION: ${OPENSCAD_SHORTVERSION}")
# message(STATUS "OPENSCAD_YEAR: ${OPENSCAD_YEAR}")
# message(STATUS "OPENSCAD_MONTH: ${OPENSCAD_MONTH}")
# message(STATUS "OPENSCAD_DAY: ${OPENSCAD_DAY}")
# message(STATUS "OPENSCAD_PATCH: ${OPENSCAD_PATCH}")
# message(STATUS "OPENSCAD_BUILD: ${OPENSCAD_BUILD}")
