name: openscad-nightly
title: OpenSCAD-Nightly
base: core24
version: "git"
summary: OpenSCAD - Design. Code. Create.
description: >
    OpenSCAD is a software for creating solid 3D CAD models. It is free software and
    available for Mac, Windows, Linux and other UNIX-like OS’es. Unlike most 3D design
    software, the focus is not on the artistic aspects of 3D design but instead on the
    CAD aspects. This might be the application you are looking for when you are planning
    to create 3D designs for machine parts but is probably not what you are looking for
    when you are more interested in creating computer-animated movies. OpenSCAD is not
    an interactive modeller. Instead it is something like a 3D-compiler that reads in
    a script file that describes your object and renders the 3D model from this script
    file. This gives you, the designer, full control over the modelling process and
    enables you to easily change any step in your process or make designs that are
    defined by configurable parameters.

    OpenSCAD provides two primary modelling techniques: Constructive solid geometry
    (aka CSG) as well as extrusion of 2D outlines. We support reading, both 2D outlines
    and 3D object from external design files, in a variety of file formats.

    NOTE: This is the development snapshot, automatically built from the source
    repository.
confinement: strict
icon: resources/icons/openscad-nightly-256.png
license: GPL-3.0
grade: stable
platforms:
  amd64:
  arm64:
  s390x:
  ppc64el:

apps:
  openscad-nightly:
    command: usr/bin/openscad-nightly
    command-chain: [ bin/desktop-launch ]
    plugs: [desktop, desktop-legacy, x11, wayland, opengl, home, audio-playback, pulseaudio, network, removable-media, joystick]
    desktop: usr/share/applications/openscad-nightly.desktop
    environment:
      DISABLE_WAYLAND: 1

parts:
  cgal:
    source: https://github.com/CGAL/cgal/releases/download/v6.0.1/CGAL-6.0.1-library.tar.xz
    plugin: cmake
    cmake-parameters: [
      "-DCMAKE_BUILD_TYPE=Release",
      "-DCMAKE_INSTALL_PREFIX=/usr",
    ]
    after: [ patches ]
    build-packages:
    - cmake
    - libboost-dev
    - libboost-thread-dev

  lib3mf2:
    source: https://github.com/3MFConsortium/lib3mf/archive/refs/tags/v2.3.1.tar.gz
    plugin: cmake
    cmake-parameters: [
      "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
      "-DCMAKE_INSTALL_PREFIX:PATH=/usr",
      "-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib",
      "-DLIB3MF_TESTS=OFF",
      "-DUSE_INCLUDED_ZLIB=OFF",
      "-DUSE_INCLUDED_LIBZIP=OFF",
    ]

  openscad-nightly:
    source: .
    build-snaps: [cmake]
    plugin: cmake
    override-build: |
        CC=clang CXX=clang++ cmake ${SNAPCRAFT_PART_SRC} \
            -G 'Unix Makefiles' \
            -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr" \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release \
            -DSUFFIX=nightly \
            -DEXPERIMENTAL=ON \
            -DSNAPSHOT=ON \
            -DUSE_BUILTIN_OPENCSG=ON
        cmake --build .
        cmake --install . --prefix "${SNAPCRAFT_PART_INSTALL}/usr"
    after: [ desktop-qt5, cgal, lib3mf2 ]
    build-packages:
    - git
    - clang
    - qtbase5-dev
    - qtmultimedia5-dev
    - libqt5svg5-dev
    - libqt5opengl5-dev
    - libqt5gamepad5-dev
    - libeigen3-dev
    - libglib2.0-dev
    - bison
    - flex
    - libglew-dev
    - libglvnd-dev
    - libgmp-dev
    - libmpfr-dev
    - libcairo2-dev
    - python3
    - libboost-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libboost-program-options-dev
    - libdouble-conversion-dev
    - chrpath
    - gettext
    - pkg-config
    - imagemagick
    - libtbb-dev
    - libzip-dev
    - libgl-dev
    - libxml2-dev
    - libharfbuzz-dev
    - libfreetype6-dev
    - libfontconfig1-dev
    - libqscintilla2-qt5-dev
    stage-packages:
    - qtwayland5
    - libasyncns0
    - libboost-regex1.83.0
    - libboost-system1.83.0
    - libboost-program-options1.83.0
    - libdouble-conversion3
    - libflac12t64
    - libglew2.2
    - libglu1-mesa
    - libglvnd0
    - libopengl0
    - libmpfr6
    - libgmpxx4ldbl
    - libogg0
    - libpulse0
    - libqt5svg5
    - libqt5opengl5
    - libqt5gamepad5
    - libqt5concurrent5
    - libqt5multimedia5
    - libqt5printsupport5
    - libqscintilla2-qt5-15
    - libsndfile1
    - libvorbis0a
    - libvorbisenc2
    - libzip4t64
    - libtbb12
    - libatomic1

  # https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  patches:
    source: snap/local/patches
    plugin: dump
    prime:
      - -*
