// Generated by OpenSCAD!
// Source file: conversion-test.scad

#version 3.7;
global_settings { assumed_gamma 1.0 }
#declare MATERIAL=finish { specular 0.5 roughness 0.001 reflection{0 0.63 fresnel} ambient 0 diffuse 0.6 conserve_energy }
#declare MATERIAL_INT=interior{ior 1.32}
polygon { 4, 
<15, 0, 0>, <20, 5, 0>, <20, 0, 0>, <15, 0, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 5, 0>, <15, 0, 0>, <15, 5, 0>, <20, 5, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 0, 5>, <15, 0, 0>, <20, 0, 0>, <20, 0, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 5, 0>, <20, 0, 5>, <20, 0, 0>, <20, 5, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<15, 0, 0>, <20, 0, 5>, <15, 0, 5>, <15, 0, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<15, 5, 5>, <15, 0, 0>, <15, 0, 5>, <15, 5, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 0, 5>, <15, 5, 5>, <15, 0, 5>, <20, 0, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<15, 0, 0>, <15, 5, 5>, <15, 5, 0>, <15, 0, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 0, 5>, <20, 5, 0>, <20, 5, 5>, <20, 0, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<15, 5, 5>, <20, 0, 5>, <20, 5, 5>, <15, 5, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<20, 5, 0>, <15, 5, 5>, <20, 5, 5>, <20, 5, 0>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<15, 5, 5>, <20, 5, 0>, <15, 5, 0>, <15, 5, 5>
texture { pigment { color rgbf <1, 0, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 5, 0>, <-25, 0, 0>, <-25, 5, 0>, <-20, 5, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 0, 0>, <-20, 5, 0>, <-20, 0, 0>, <-25, 0, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 5, 0>, <-25, 5, 5>, <-20, 5, 5>, <-20, 5, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 5, 5>, <-20, 5, 0>, <-25, 5, 0>, <-25, 5, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 5, 5>, <-20, 0, 5>, <-20, 5, 5>, <-25, 5, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 0, 5>, <-20, 5, 0>, <-20, 5, 5>, <-20, 0, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 0, 0>, <-25, 5, 5>, <-25, 5, 0>, <-25, 0, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 0, 5>, <-25, 5, 5>, <-25, 0, 5>, <-20, 0, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 5, 5>, <-25, 0, 0>, <-25, 0, 5>, <-25, 5, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-25, 0, 0>, <-20, 0, 5>, <-25, 0, 5>, <-25, 0, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 5, 0>, <-20, 0, 5>, <-20, 0, 0>, <-20, 5, 0>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-20, 0, 5>, <-25, 0, 0>, <-20, 0, 0>, <-20, 0, 5>
texture { pigment { color rgbf <1, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 5, -10>, <5, 0, -5>, <5, 0, -10>, <5, 5, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 5, -10>, <0, 5, -5>, <5, 5, -5>, <5, 5, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 5, -5>, <5, 5, -10>, <0, 5, -10>, <0, 5, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 0, -5>, <0, 5, -5>, <0, 0, -5>, <5, 0, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 0, -5>, <5, 5, -10>, <5, 5, -5>, <5, 0, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 0, -10>, <5, 5, -10>, <5, 0, -10>, <0, 0, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 0, -5>, <0, 0, -10>, <5, 0, -10>, <5, 0, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<5, 5, -10>, <0, 0, -10>, <0, 5, -10>, <5, 5, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 0, -10>, <0, 5, -5>, <0, 5, -10>, <0, 0, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 0, -10>, <5, 0, -5>, <0, 0, -5>, <0, 0, -10>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 5, -5>, <0, 0, -10>, <0, 0, -5>, <0, 5, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 5, -5>, <5, 0, -5>, <5, 5, -5>, <0, 5, -5>
texture { pigment { color rgbf <1, 0, 1, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 20, 0>, <-5, 20, 5>, <0, 20, 5>, <0, 20, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 20, 5>, <0, 15, 5>, <0, 20, 5>, <-5, 20, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 15, 5>, <0, 20, 0>, <0, 20, 5>, <0, 15, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 20, 0>, <0, 15, 5>, <0, 15, 0>, <0, 20, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 15, 5>, <-5, 15, 0>, <0, 15, 0>, <0, 15, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 15, 0>, <0, 20, 0>, <0, 15, 0>, <-5, 15, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 20, 0>, <-5, 15, 0>, <-5, 20, 0>, <0, 20, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 15, 0>, <0, 15, 5>, <-5, 15, 5>, <-5, 15, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 20, 5>, <-5, 15, 0>, <-5, 15, 5>, <-5, 20, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<0, 15, 5>, <-5, 20, 5>, <-5, 15, 5>, <0, 15, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 15, 0>, <-5, 20, 5>, <-5, 20, 0>, <-5, 15, 0>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
polygon { 4, 
<-5, 20, 5>, <0, 20, 0>, <-5, 20, 0>, <-5, 20, 5>
texture { pigment { color rgbf <0, 1, 0, 0> } }
finish { MATERIAL } interior { MATERIAL_INT }
}
light_source { <-71.3684, -41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, -41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, -41.0485, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 0, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 0, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 0, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <-71.3684, 41.0485, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, -41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, -41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <0, -41.0485, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 0, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 0, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 0, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <0, 41.0485, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, -41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, -41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, -41.0485, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 0, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 0, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 0, 25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 41.0485, -25> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 41.0485, 0> color rgb <0.2, 0.2, 0.2> }
light_source { <71.3684, 41.0485, 25> color rgb <0.2, 0.2, 0.2> }
camera { look_at <0, 0, 0> location <0, -98.6405, 0> up <0, 0, 1> right <1, 0, 0> sky <0, 0, 1> rotate <-55, clock * 3, clock + 25> }
#include "rad_def.inc"
global_settings { photons { count 20000 autostop 0 jitter .4 } radiosity { Rad_Settings(Radiosity_Normal, off, off) } }
