"""Regression fixture for the in-script ``export()`` function: POV-Ray.

The ``.pov`` suffix routes through ``fileformat::fromIdentifier()`` to
``FileFormat::POV`` in ``python_export_core()``. POV's ``Generated by``
header uses the hard-coded ``EXPORT_CREATOR`` constant, so the file is
already PythonSCAD/OpenSCAD-neutral in practice; the driver still runs
``post_process_progname`` defensively (registered via
``_POST_PROCESSORS[".pov"]``) so future header changes do not silently
break goldens.
"""
from pythonscad import cube, export

export(cube(5), "cube.pov")
